version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Ejecutando pruebas"
      - pytest tests/ || echo "No hay pruebas definidas"
  post_build:
    commands:
      - echo "Construcción finalizada con éxito"

